"""View mode toggle bar — switches between Input/Alpha/FG/Matte/Comp/Processed.

Uses QButtonGroup with exclusive selection. Active button highlighted
with brand yellow. Buttons are enabled/disabled based on which output
directories actually have frames (via FrameIndex availability).
"""
from __future__ import annotations

from PySide6.QtWidgets import QWidget, QHBoxLayout, QPushButton, QButtonGroup
from PySide6.QtCore import Signal

from ui.preview.frame_index import ViewMode


# Display labels for each mode
_MODE_LABELS: dict[ViewMode, str] = {
    ViewMode.INPUT: "INPUT",
    ViewMode.MASK: "MASK",
    ViewMode.ALPHA: "ALPHA",
    ViewMode.FG: "FG",
    ViewMode.MATTE: "MATTE",
    ViewMode.COMP: "COMP",
    ViewMode.PROCESSED: "PROC",
}

_MODE_TOOLTIPS: dict[ViewMode, str] = {
    ViewMode.INPUT: "Original input footage (unprocessed)\n\nHotkey: F1",
    ViewMode.MASK: (
        "Tracked mask — SAM2 segmentation output.\n"
        "White = foreground, black = background.\n"
        "This is the binary mask before MatAnyone2/VideoMaMa refinement.\n\n"
        "Hotkey: F2"
    ),
    ViewMode.ALPHA: (
        "Alpha hint — generated by GVM, VideoMaMa, or MatAnyone2.\n"
        "White = foreground, black = background.\n"
        "This is the pre-inference guide used by CorridorKey.\n\n"
        "Hotkey: F3"
    ),
    ViewMode.FG: (
        "Foreground — subject with green spill removed.\n"
        "Colors may look shifted; this is the despilled intermediate.\n\n"
        "Hotkey: F4"
    ),
    ViewMode.MATTE: (
        "Alpha matte — white = opaque, black = transparent.\n"
        "Shows the AI's confidence in foreground vs background.\n\n"
        "Hotkey: F5"
    ),
    ViewMode.COMP: (
        "Composite — final keyed result over checkerboard.\n"
        "Best preview of key quality with faithful colors.\n\n"
        "Hotkey: F6"
    ),
    ViewMode.PROCESSED: (
        "Processed — production RGBA (straight, linear).\n"
        "For Resolve, Premiere, and compositing tools.\n"
        "Preview composites the stored image over black.\n"
        "Final compositing should happen in your compositor of choice.\n\n"
        "Hotkey: F7"
    ),
}


class ViewModeBar(QWidget):
    """Horizontal bar of toggle buttons for preview view modes.

    Button visual state has three tiers:

    * **Disabled** — clip contains zero frames for this mode. Unclickable.
    * **Dim** — clip has frames for this mode but not at the current stem.
      Still clickable so the user can switch and see the placeholder.
    * **Normal / Active** — clip has a frame for this mode at the current
      stem. Active (selected) mode is highlighted in brand yellow.

    Callers update availability at two granularities:

    * :meth:`set_available_modes` — clip-level: enable/disable based on which
      modes have *any* frames in the whole clip.
    * :meth:`set_current_stem_availability` — per-stem: dim the enabled
      buttons whose mode has no frame at the currently displayed stem.
    """

    mode_changed = Signal(str)  # emits ViewMode.value

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedHeight(30)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(8, 2, 8, 2)
        layout.setSpacing(2)

        self._button_group = QButtonGroup(self)
        self._button_group.setExclusive(True)
        self._buttons: dict[ViewMode, QPushButton] = {}
        # Tracks whether the current stem has a frame for this mode. Used
        # by _refresh_button_style to decide between "normal" and "dim".
        self._stem_present: dict[ViewMode, bool] = {m: True for m in ViewMode}

        for i, mode in enumerate(ViewMode):
            btn = QPushButton(_MODE_LABELS[mode])
            btn.setCheckable(True)
            btn.setEnabled(False)
            btn.setFixedHeight(24)
            btn.setMinimumWidth(50)
            btn.setStyleSheet(self._button_style(False))
            btn.setToolTip(_MODE_TOOLTIPS.get(mode, ""))
            self._buttons[mode] = btn
            self._button_group.addButton(btn, i)
            layout.addWidget(btn)

        # Default to COMP
        self._buttons[ViewMode.COMP].setChecked(True)

        self._button_group.idClicked.connect(self._on_mode_clicked)
        layout.addStretch()


    def set_available_modes(self, modes: list[ViewMode]) -> None:
        """Enable buttons for modes that have frames anywhere in the clip."""
        mode_set = set(modes)
        for mode, btn in self._buttons.items():
            btn.setEnabled(mode in mode_set)
            # Clip-level re-eval resets per-stem tracking: assume present
            # until the caller tells us otherwise via the per-stem API.
            self._stem_present[mode] = mode in mode_set
            self._refresh_button_style(mode)

        # If current mode is unavailable, switch to the most useful fallback.
        current = self.current_mode()
        if current not in mode_set and mode_set:
            # Prefer final outputs first, then AlphaHint, then source views.
            for fallback in [ViewMode.COMP, ViewMode.ALPHA, ViewMode.INPUT]:
                if fallback in mode_set:
                    self._buttons[fallback].setChecked(True)
                    self._on_mode_clicked(list(ViewMode).index(fallback))
                    return
            first = list(mode_set)[0]
            self._buttons[first].setChecked(True)
            self._on_mode_clicked(list(ViewMode).index(first))

    def set_current_stem_availability(self, modes_with_current_frame) -> None:
        """Per-stem dim update.

        Called on every scrub. Modes that are clip-level enabled but whose
        current stem has no frame get dimmed (still clickable). Modes with
        a frame at the current stem render normally. Disabled modes are
        unaffected.

        Args:
            modes_with_current_frame: Iterable of :class:`ViewMode` values
                that have a frame at the currently displayed stem.
        """
        present_set = set(modes_with_current_frame)
        for mode in self._buttons:
            self._stem_present[mode] = mode in present_set
            self._refresh_button_style(mode)

    def current_mode(self) -> ViewMode:
        """Return the currently selected ViewMode."""
        checked_id = self._button_group.checkedId()
        if checked_id >= 0:
            return list(ViewMode)[checked_id]
        return ViewMode.COMP

    def _on_mode_clicked(self, button_id: int) -> None:
        mode = list(ViewMode)[button_id]
        # Refresh all buttons — active state changed, stem_present unchanged.
        for m in self._buttons:
            self._refresh_button_style(m)
        self.mode_changed.emit(mode.value)

    def _refresh_button_style(self, mode: ViewMode) -> None:
        """Re-apply stylesheet for one button based on active + stem_present."""
        btn = self._buttons[mode]
        is_active = (self.current_mode() == mode)
        stem_present = self._stem_present.get(mode, True)
        btn.setStyleSheet(self._button_style(is_active, stem_present=stem_present))

    @staticmethod
    def _button_style(active: bool, stem_present: bool = True) -> str:
        if active:
            return (
                "QPushButton { background-color: #FFF203; color: #000000; "
                "font-weight: 700; font-size: 10px; padding: 2px 6px; border: none; }"
            )
        if not stem_present:
            # Enabled (clickable) but no frame at current stem — dimmed.
            return (
                "QPushButton { background-color: #141300; color: #4A4A35; "
                "font-size: 10px; padding: 2px 6px; border: 1px solid #1F1E08; }"
                "QPushButton:hover { border-color: #2A2910; color: #606050; }"
                "QPushButton:disabled { color: #2A2A20; border-color: #141300; }"
            )
        return (
            "QPushButton { background-color: #1A1900; color: #808070; "
            "font-size: 10px; padding: 2px 6px; border: 1px solid #2A2910; }"
            "QPushButton:hover { border-color: #454430; color: #E0E0E0; }"
            "QPushButton:disabled { color: #3A3A30; border-color: #1A1900; }"
        )
